import { Blockchain, BridgeChain, SwapChain } from "@circle-fin/app-kit";

export type NetworkTier = "mainnet" | "testnet";
export type RuntimeMode = "browser-evm" | "solana-adapter";

export type ChainSupport = {
  label: string;
  tier: NetworkTier;
  chain: Blockchain;
  bridgeValue: BridgeChain;
  swapValue: SwapChain | null;
  send: boolean;
  bridge: boolean;
  swap: boolean;
  chainAdapters: boolean;
  circleWallets: boolean;
  runtimeMode: RuntimeMode;
};

export const chainCatalog: ReadonlyArray<ChainSupport> = [
  {
    label: "Arbitrum",
    tier: "mainnet",
    chain: Blockchain.Arbitrum,
    bridgeValue: BridgeChain.Arbitrum,
    swapValue: SwapChain.Arbitrum,
    send: true,
    bridge: true,
    swap: true,
    chainAdapters: true,
    circleWallets: true,
    runtimeMode: "browser-evm",
  },
  {
    label: "Avalanche",
    tier: "mainnet",
    chain: Blockchain.Avalanche,
    bridgeValue: BridgeChain.Avalanche,
    swapValue: SwapChain.Avalanche,
    send: true,
    bridge: true,
    swap: true,
    chainAdapters: true,
    circleWallets: true,
    runtimeMode: "browser-evm",
  },
  {
    label: "Base",
    tier: "mainnet",
    chain: Blockchain.Base,
    bridgeValue: BridgeChain.Base,
    swapValue: SwapChain.Base,
    send: true,
    bridge: true,
    swap: true,
    chainAdapters: true,
    circleWallets: true,
    runtimeMode: "browser-evm",
  },
  {
    label: "Codex",
    tier: "mainnet",
    chain: Blockchain.Codex,
    bridgeValue: BridgeChain.Codex,
    swapValue: null,
    send: true,
    bridge: true,
    swap: false,
    chainAdapters: true,
    circleWallets: false,
    runtimeMode: "browser-evm",
  },
  {
    label: "EDGE",
    tier: "mainnet",
    chain: Blockchain.Edge,
    bridgeValue: BridgeChain.Edge,
    swapValue: null,
    send: true,
    bridge: true,
    swap: false,
    chainAdapters: true,
    circleWallets: false,
    runtimeMode: "browser-evm",
  },
  {
    label: "Ethereum",
    tier: "mainnet",
    chain: Blockchain.Ethereum,
    bridgeValue: BridgeChain.Ethereum,
    swapValue: SwapChain.Ethereum,
    send: true,
    bridge: true,
    swap: true,
    chainAdapters: true,
    circleWallets: true,
    runtimeMode: "browser-evm",
  },
  {
    label: "HyperEVM",
    tier: "mainnet",
    chain: Blockchain.HyperEVM,
    bridgeValue: BridgeChain.HyperEVM,
    swapValue: SwapChain.HyperEVM,
    send: true,
    bridge: true,
    swap: true,
    chainAdapters: true,
    circleWallets: false,
    runtimeMode: "browser-evm",
  },
  {
    label: "Ink",
    tier: "mainnet",
    chain: Blockchain.Ink,
    bridgeValue: BridgeChain.Ink,
    swapValue: SwapChain.Ink,
    send: true,
    bridge: true,
    swap: true,
    chainAdapters: true,
    circleWallets: false,
    runtimeMode: "browser-evm",
  },
  {
    label: "Linea",
    tier: "mainnet",
    chain: Blockchain.Linea,
    bridgeValue: BridgeChain.Linea,
    swapValue: SwapChain.Linea,
    send: true,
    bridge: true,
    swap: true,
    chainAdapters: true,
    circleWallets: false,
    runtimeMode: "browser-evm",
  },
  {
    label: "Monad",
    tier: "mainnet",
    chain: Blockchain.Monad,
    bridgeValue: BridgeChain.Monad,
    swapValue: SwapChain.Monad,
    send: true,
    bridge: true,
    swap: true,
    chainAdapters: false,
    circleWallets: false,
    runtimeMode: "browser-evm",
  },
  {
    label: "Morph",
    tier: "mainnet",
    chain: Blockchain.Morph,
    bridgeValue: BridgeChain.Morph,
    swapValue: null,
    send: true,
    bridge: true,
    swap: false,
    chainAdapters: false,
    circleWallets: false,
    runtimeMode: "browser-evm",
  },
  {
    label: "OP Mainnet",
    tier: "mainnet",
    chain: Blockchain.Optimism,
    bridgeValue: BridgeChain.Optimism,
    swapValue: SwapChain.Optimism,
    send: true,
    bridge: true,
    swap: true,
    chainAdapters: true,
    circleWallets: true,
    runtimeMode: "browser-evm",
  },
  {
    label: "Plume",
    tier: "mainnet",
    chain: Blockchain.Plume,
    bridgeValue: BridgeChain.Plume,
    swapValue: SwapChain.Plume,
    send: true,
    bridge: true,
    swap: true,
    chainAdapters: true,
    circleWallets: false,
    runtimeMode: "browser-evm",
  },
  {
    label: "Polygon PoS",
    tier: "mainnet",
    chain: Blockchain.Polygon,
    bridgeValue: BridgeChain.Polygon,
    swapValue: SwapChain.Polygon,
    send: true,
    bridge: true,
    swap: true,
    chainAdapters: true,
    circleWallets: true,
    runtimeMode: "browser-evm",
  },
  {
    label: "Sei",
    tier: "mainnet",
    chain: Blockchain.Sei,
    bridgeValue: BridgeChain.Sei,
    swapValue: SwapChain.Sei,
    send: true,
    bridge: true,
    swap: true,
    chainAdapters: true,
    circleWallets: false,
    runtimeMode: "browser-evm",
  },
  {
    label: "Solana",
    tier: "mainnet",
    chain: Blockchain.Solana,
    bridgeValue: BridgeChain.Solana,
    swapValue: SwapChain.Solana,
    send: true,
    bridge: true,
    swap: true,
    chainAdapters: true,
    circleWallets: true,
    runtimeMode: "solana-adapter",
  },
  {
    label: "Sonic",
    tier: "mainnet",
    chain: Blockchain.Sonic,
    bridgeValue: BridgeChain.Sonic,
    swapValue: SwapChain.Sonic,
    send: true,
    bridge: true,
    swap: true,
    chainAdapters: true,
    circleWallets: false,
    runtimeMode: "browser-evm",
  },
  {
    label: "Unichain",
    tier: "mainnet",
    chain: Blockchain.Unichain,
    bridgeValue: BridgeChain.Unichain,
    swapValue: SwapChain.Unichain,
    send: true,
    bridge: true,
    swap: true,
    chainAdapters: true,
    circleWallets: true,
    runtimeMode: "browser-evm",
  },
  {
    label: "World Chain",
    tier: "mainnet",
    chain: Blockchain.World_Chain,
    bridgeValue: BridgeChain.World_Chain,
    swapValue: SwapChain.World_Chain,
    send: true,
    bridge: true,
    swap: true,
    chainAdapters: true,
    circleWallets: false,
    runtimeMode: "browser-evm",
  },
  {
    label: "XDC",
    tier: "mainnet",
    chain: Blockchain.XDC,
    bridgeValue: BridgeChain.XDC,
    swapValue: SwapChain.XDC,
    send: true,
    bridge: true,
    swap: true,
    chainAdapters: true,
    circleWallets: false,
    runtimeMode: "browser-evm",
  },
  {
    label: "Arbitrum Sepolia",
    tier: "testnet",
    chain: Blockchain.Arbitrum_Sepolia,
    bridgeValue: BridgeChain.Arbitrum_Sepolia,
    swapValue: null,
    send: true,
    bridge: true,
    swap: false,
    chainAdapters: true,
    circleWallets: true,
    runtimeMode: "browser-evm",
  },
  {
    label: "Arc Testnet",
    tier: "testnet",
    chain: Blockchain.Arc_Testnet,
    bridgeValue: BridgeChain.Arc_Testnet,
    swapValue: SwapChain.Arc_Testnet,
    send: true,
    bridge: true,
    swap: true,
    chainAdapters: true,
    circleWallets: true,
    runtimeMode: "browser-evm",
  },
  {
    label: "Avalanche Fuji",
    tier: "testnet",
    chain: Blockchain.Avalanche_Fuji,
    bridgeValue: BridgeChain.Avalanche_Fuji,
    swapValue: null,
    send: true,
    bridge: true,
    swap: false,
    chainAdapters: true,
    circleWallets: true,
    runtimeMode: "browser-evm",
  },
  {
    label: "Base Sepolia",
    tier: "testnet",
    chain: Blockchain.Base_Sepolia,
    bridgeValue: BridgeChain.Base_Sepolia,
    swapValue: null,
    send: true,
    bridge: true,
    swap: false,
    chainAdapters: true,
    circleWallets: true,
    runtimeMode: "browser-evm",
  },
  {
    label: "Codex Testnet",
    tier: "testnet",
    chain: Blockchain.Codex_Testnet,
    bridgeValue: BridgeChain.Codex_Testnet,
    swapValue: null,
    send: true,
    bridge: true,
    swap: false,
    chainAdapters: true,
    circleWallets: false,
    runtimeMode: "browser-evm",
  },
  {
    label: "EDGE Testnet",
    tier: "testnet",
    chain: Blockchain.Edge_Testnet,
    bridgeValue: BridgeChain.Edge_Testnet,
    swapValue: null,
    send: true,
    bridge: true,
    swap: false,
    chainAdapters: true,
    circleWallets: false,
    runtimeMode: "browser-evm",
  },
  {
    label: "Ethereum Sepolia",
    tier: "testnet",
    chain: Blockchain.Ethereum_Sepolia,
    bridgeValue: BridgeChain.Ethereum_Sepolia,
    swapValue: null,
    send: true,
    bridge: true,
    swap: false,
    chainAdapters: true,
    circleWallets: true,
    runtimeMode: "browser-evm",
  },
  {
    label: "HyperEVM Testnet",
    tier: "testnet",
    chain: Blockchain.HyperEVM_Testnet,
    bridgeValue: BridgeChain.HyperEVM_Testnet,
    swapValue: null,
    send: true,
    bridge: true,
    swap: false,
    chainAdapters: true,
    circleWallets: false,
    runtimeMode: "browser-evm",
  },
  {
    label: "Ink Testnet",
    tier: "testnet",
    chain: Blockchain.Ink_Testnet,
    bridgeValue: BridgeChain.Ink_Testnet,
    swapValue: null,
    send: true,
    bridge: true,
    swap: false,
    chainAdapters: true,
    circleWallets: false,
    runtimeMode: "browser-evm",
  },
  {
    label: "Linea Sepolia",
    tier: "testnet",
    chain: Blockchain.Linea_Sepolia,
    bridgeValue: BridgeChain.Linea_Sepolia,
    swapValue: null,
    send: true,
    bridge: true,
    swap: false,
    chainAdapters: true,
    circleWallets: false,
    runtimeMode: "browser-evm",
  },
  {
    label: "Monad Testnet",
    tier: "testnet",
    chain: Blockchain.Monad_Testnet,
    bridgeValue: BridgeChain.Monad_Testnet,
    swapValue: null,
    send: true,
    bridge: true,
    swap: false,
    chainAdapters: false,
    circleWallets: false,
    runtimeMode: "browser-evm",
  },
  {
    label: "Morph Testnet",
    tier: "testnet",
    chain: Blockchain.Morph_Testnet,
    bridgeValue: BridgeChain.Morph_Testnet,
    swapValue: null,
    send: true,
    bridge: true,
    swap: false,
    chainAdapters: false,
    circleWallets: false,
    runtimeMode: "browser-evm",
  },
  {
    label: "OP Sepolia",
    tier: "testnet",
    chain: Blockchain.Optimism_Sepolia,
    bridgeValue: BridgeChain.Optimism_Sepolia,
    swapValue: null,
    send: true,
    bridge: true,
    swap: false,
    chainAdapters: true,
    circleWallets: true,
    runtimeMode: "browser-evm",
  },
  {
    label: "Plume Testnet",
    tier: "testnet",
    chain: Blockchain.Plume_Testnet,
    bridgeValue: BridgeChain.Plume_Testnet,
    swapValue: null,
    send: true,
    bridge: true,
    swap: false,
    chainAdapters: true,
    circleWallets: false,
    runtimeMode: "browser-evm",
  },
  {
    label: "Polygon PoS Amoy",
    tier: "testnet",
    chain: Blockchain.Polygon_Amoy_Testnet,
    bridgeValue: BridgeChain.Polygon_Amoy_Testnet,
    swapValue: null,
    send: true,
    bridge: true,
    swap: false,
    chainAdapters: true,
    circleWallets: true,
    runtimeMode: "browser-evm",
  },
  {
    label: "Sei Testnet",
    tier: "testnet",
    chain: Blockchain.Sei_Testnet,
    bridgeValue: BridgeChain.Sei_Testnet,
    swapValue: null,
    send: true,
    bridge: true,
    swap: false,
    chainAdapters: true,
    circleWallets: false,
    runtimeMode: "browser-evm",
  },
  {
    label: "Solana Devnet",
    tier: "testnet",
    chain: Blockchain.Solana_Devnet,
    bridgeValue: BridgeChain.Solana_Devnet,
    swapValue: null,
    send: true,
    bridge: true,
    swap: false,
    chainAdapters: true,
    circleWallets: true,
    runtimeMode: "solana-adapter",
  },
  {
    label: "Sonic Testnet",
    tier: "testnet",
    chain: Blockchain.Sonic_Testnet,
    bridgeValue: BridgeChain.Sonic_Testnet,
    swapValue: null,
    send: true,
    bridge: true,
    swap: false,
    chainAdapters: true,
    circleWallets: false,
    runtimeMode: "browser-evm",
  },
  {
    label: "Unichain Sepolia",
    tier: "testnet",
    chain: Blockchain.Unichain_Sepolia,
    bridgeValue: BridgeChain.Unichain_Sepolia,
    swapValue: null,
    send: true,
    bridge: true,
    swap: false,
    chainAdapters: true,
    circleWallets: true,
    runtimeMode: "browser-evm",
  },
  {
    label: "World Chain Sepolia",
    tier: "testnet",
    chain: Blockchain.World_Chain_Sepolia,
    bridgeValue: BridgeChain.World_Chain_Sepolia,
    swapValue: null,
    send: true,
    bridge: true,
    swap: false,
    chainAdapters: true,
    circleWallets: false,
    runtimeMode: "browser-evm",
  },
  {
    label: "XDC Apothem",
    tier: "testnet",
    chain: Blockchain.XDC_Apothem,
    bridgeValue: BridgeChain.XDC_Apothem,
    swapValue: null,
    send: true,
    bridge: true,
    swap: false,
    chainAdapters: true,
    circleWallets: false,
    runtimeMode: "browser-evm",
  },
];

export const mainnetChains = chainCatalog.filter((chain) => chain.tier === "mainnet");
export const testnetChains = chainCatalog.filter((chain) => chain.tier === "testnet");
export const liveBrowserChains = chainCatalog.filter(
  (chain) => chain.runtimeMode === "browser-evm",
);
export const liveBridgeChains = liveBrowserChains.filter((chain) => chain.bridge);
export const liveSwapChains = liveBrowserChains.filter((chain) => chain.swap);
export const liveSendChains = liveBrowserChains.filter((chain) => chain.send);
